// Jolly Phonics Dashboard — Data
window.JP = {

sounds: {
  's':      {e:'🐍', a:'Weave hand like a snake: ssss',        w:['sat','sit','sun','bus']},
  'a':      {e:'🐜', a:'Cup hand to ear: a a a!',              w:['ant','and','can','hat']},
  't':      {e:'🥁', a:'Turn head side to side: t t t',        w:['tap','top','bat','sit']},
  'i':      {e:'🐛', a:'Wriggle finger by nose: i i i',        w:['it','in','tip','sit']},
  'p':      {e:'💨', a:'Blow gently away: p p p',              w:['pat','pan','cap','tap']},
  'n':      {e:'✈️', a:'Arms out like an aeroplane: nnn',      w:['nap','net','run','tin']},
  'ck':     {e:'🎸', a:'Click fingers together: ck ck ck',     w:['duck','back','sock','tick']},
  'e':      {e:'🥚', a:'Tap elbow with hand: e e e',           w:['egg','end','pet','hen']},
  'h':      {e:'🐕', a:'Pant like a dog: h h h',               w:['hat','him','hot','his']},
  'r':      {e:'🐾', a:'Growl like a dog: rrr',                w:['rat','run','red','rip']},
  'm':      {e:'😋', a:'Rub tummy — mmm yummy!',               w:['man','mud','him','drum']},
  'd':      {e:'🥁', a:'Beat a drum with both hands: d d d',   w:['dog','did','dip','mud']},
  'g':      {e:'🌀', a:'Spiral hand like water down a drain',  w:['got','gap','big','dog']},
  'o':      {e:'🔴', a:'Round your lips in a circle: o o o',   w:['on','off','hot','top']},
  'u':      {e:'⬆️', a:'Lift both hands upward: u u u',        w:['up','us','cup','run']},
  'l':      {e:'🍭', a:'Lick a lollipop: lll lll',             w:['lip','leg','let','hill']},
  'f':      {e:'🦈', a:'Hold arms out like shark fins: fff',   w:['fat','fit','off','if']},
  'b':      {e:'📚', a:'Hold hands flat like book covers: b',  w:['bat','big','bus','cob']},
  'ai':     {e:'🫏', a:'Flap hands like donkey ears: ai',      w:['rain','tail','main','pain']},
  'j':      {e:'🍮', a:'Wobble body like jelly: j j j',        w:['jam','jet','jog','just']},
  'oa':     {e:'⛵', a:'Cup mouth and say: oh oh oh',          w:['boat','coat','road','goat']},
  'ie':     {e:'🫡', a:'Stand to attention and salute: ie',    w:['tie','die','pie','lie']},
  'ee':     {e:'🐝', a:'Flap hands at sides of head: ee',      w:['bee','see','feet','deep']},
  'or':     {e:'🚣', a:'Row a boat with both arms: or',        w:['for','corn','born','sort']},
  'z':      {e:'🤐', a:'Zip up jacket from bottom: zzz',       w:['zip','zap','jazz','buzz']},
  'w':      {e:'💨', a:'Blow wind with both hands: www',       w:['wet','win','wag','swim']},
  'ng':     {e:'💪', a:'Flex muscles like a strongman: ng',    w:['ring','sing','long','bang']},
  'v':      {e:'🧹', a:'Rev like a vacuum cleaner: vvv',       w:['van','vet','vine','give']},
  'oo':     {e:'📖', a:'Point fingers together (short oo)',    w:['book','cook','look','foot']},
  'oo2':    {e:'🌙', a:'Move head side to side (long oo)',      w:['moon','soon','food','cool']},
  'y':      {e:'😪', a:'Yawn and stretch arms above head',     w:['yes','yet','yell','yap']},
  'x':      {e:'🦴', a:'Take an X-ray of someone: ks ks',      w:['fox','box','mix','six']},
  'ch':     {e:'🚂', a:'Move arms like train wheels: ch ch',   w:['chip','chop','much','such']},
  'sh':     {e:'🤫', a:'Hold finger to lips: shhhh!',          w:['ship','shop','fish','dish']},
  'th':     {e:'👅', a:'Tongue out, breathe softly (voiced)',  w:['the','this','that','then']},
  'th2':    {e:'👅', a:'Tongue out, breathe hard (unvoiced)',  w:['thin','thick','moth','math']},
  'qu':     {e:'🦆', a:'Make a duck beak with both hands',     w:['quiz','quit','queen','quill']},
  'ou':     {e:'🔥', a:'Pretend to touch something hot: ou!',  w:['out','our','shout','found']},
  'oi':     {e:'🫙', a:'Wring a wet cloth with both hands',    w:['oil','boil','coin','join']},
  'ue':     {e:'👆', a:'Point to people around you: ue',       w:['cue','due','fuel','blue']},
  'er':     {e:'🌀', a:'Roll hands like a mixer: er-er-er',    w:['her','fern','verb','stern']},
  'ar':     {e:'🦷', a:'Open mouth wide like at the dentist!', w:['car','bar','farm','dark']},
  // Capitals
  'S':      {e:'🐍', a:'Capital S — same snake action!',       w:['Sun','Sam','Six','Sit']},
  'A':      {e:'🐜', a:'Capital A — ant starts with A!',       w:['And','An','At','As']},
  'T':      {e:'🌲', a:'Capital T — tall straight T!',         w:['Top','Ten','Tap','Tim']},
  'I':      {e:'📏', a:'Capital I — stands tall & straight',   w:['In','It','Is','If']},
  'P':      {e:'💨', a:'Capital P — puffing P!',               w:['Put','Pat','Pen','Pan']},
  'N':      {e:'✈️', a:'Capital N — aeroplane arms!',          w:['Not','Now','Net','Nap']},
  'CK':     {e:'🎸', a:'Capital C & K — clicking sounds!',     w:['Can','Cat','Kid','Kit']},
  'E':      {e:'🥚', a:'Capital E — egg starts with E!',       w:['End','Egg','Eat','Every']},
  'H':      {e:'🐕', a:'Capital H — panting H!',               w:['Him','Hot','Hat','Has']},
  'R':      {e:'🐾', a:'Capital R — growling R!',              w:['Run','Red','Rat','Rip']},
  'M':      {e:'😋', a:'Capital M — mmm yummy M!',             w:['Man','Mud','Met','My']},
  'D':      {e:'🥁', a:'Capital D — drum D!',                  w:['Dog','Did','Dig','Dip']},
  'G':      {e:'🌀', a:'Capital G — drain G!',                 w:['Got','Gap','Gas','Get']},
  'O':      {e:'🔴', a:'Capital O — round O!',                 w:['On','Off','Old','Own']},
  'U':      {e:'⬆️', a:'Capital U — lifting up!',              w:['Up','Us','Under','Upon']},
  'L':      {e:'🍭', a:'Capital L — lollipop L!',              w:['Let','Lip','Leg','Log']},
  'F':      {e:'🦈', a:'Capital F — shark fins F!',            w:['Fat','Fit','For','Fun']},
  'B':      {e:'📚', a:'Capital B — bookworm B!',              w:['Bat','Big','Bus','Bit']},
  'J':      {e:'🍮', a:'Capital J — jelly J!',                 w:['Jam','Jet','Jog','Just']},
  'W':      {e:'💨', a:'Capital W — windy W!',                 w:['Wet','Win','Was','We']},
  'V':      {e:'🧹', a:'Capital V — vacuum V!',                w:['Van','Vet','Very','Vine']},
  'Y':      {e:'😪', a:'Capital Y — yawning Y!',               w:['Yes','Yet','You','Your']},
  'Q':      {e:'🦆', a:'Capital Q — quacking Q!',              w:['Queen','Quiz','Quit','Quick']},
  'Z':      {e:'🤐', a:'Capital Z — zip Z!',                   w:['Zoo','Zero','Zap','Zoom']},
  'X':      {e:'🦴', a:'Capital X — X-ray X!',                 w:['Fox','Box','Mix','Six']},
  // Alternatives
  'ay':     {e:'🌅', a:'Alternative spelling for /ai/ sound',  w:['day','play','stay','tray']},
  'a_e':    {e:'🎂', a:'Magic e — makes vowel say its name',   w:['cake','lake','gate','same']},
  'oy':     {e:'🎮', a:'Alternative spelling for /oi/ sound',  w:['boy','toy','joy','enjoy']},
  'o_e':    {e:'🦴', a:'Magic e — long /o/ sound',             w:['bone','home','rope','hope']},
  'ea':     {e:'🫖', a:'Alternative for long /ee/ sound',      w:['tea','sea','leaf','bean']},
  'e_e':    {e:'🌿', a:'Magic e — long /ee/ sound',            w:['these','theme','scheme','swede']},
  'i_e':    {e:'🪁', a:'Magic e — long /ie/ sound',            w:['kite','bike','time','smile']},
  'igh':    {e:'💡', a:'Alternative spelling for /ie/ sound',  w:['high','light','night','bright']},
  'y(ie)':  {e:'🌤️', a:'"y" making the /ie/ sound',           w:['fly','sky','cry','try']},
  'y(ee)':  {e:'👶', a:'"y" making the /ee/ sound at end',     w:['body','funny','daddy','baby']},
  'u_e':    {e:'🧊', a:'Magic e — long /oo/ or /ue/ sound',    w:['cube','mule','fuse','tune']},
  'ew':     {e:'💫', a:'Alternative for /oo/ or /ue/ sound',   w:['few','new','dew','brew']},
  'ow(ou)': {e:'🦉', a:'"ow" making the /ou/ sound',           w:['cow','town','clown','owl']},
  'ow(oh)': {e:'⛄', a:'"ow" making the /oa/ sound',           w:['snow','low','grow','throw']},
  'aw':     {e:'🎨', a:'Alternative for the /or/ sound',       w:['draw','claw','saw','yawn']},
  'au':     {e:'🍂', a:'Alternative for the /or/ sound',       w:['August','pause','sauce','cause']},
  'al':     {e:'⚽', a:'"al" making the /or/ sound',           w:['ball','talk','walk','chalk']},
  'ir':     {e:'🐦', a:'Alternative for the /er/ sound',       w:['bird','first','girl','shirt']},
  'ur':     {e:'🌀', a:'Alternative for the /er/ sound',       w:['turn','curl','hurt','purse']},
  'oe':     {e:'🦶', a:'Alternative for the /oa/ sound',       w:['toe','foe','doe','goes']},
  'ey':     {e:'🔑', a:'"ey" making the /ee/ sound',           w:['key','monkey','honey','valley']},
  'ui':     {e:'🍊', a:'Alternative for the /oo/ sound',       w:['fruit','suit','juice','bruise']},
  'air':    {e:'💨', a:'The /air/ sound',                      w:['air','hair','fair','pair']},
  'are':    {e:'👀', a:'"are" making the /air/ sound',         w:['care','dare','share','stare']},
  'ear':    {e:'👂', a:'"ear" making the /air/ sound',         w:['bear','pear','wear','swear']},
  'eigh':   {e:'🎿', a:'"eigh" making the /ai/ sound',         w:['eight','weigh','neigh','sleigh']},
  'augh':   {e:'😄', a:'"augh" making the /aw/ sound',         w:['taught','caught','daughter','naughty']},
  'ough':   {e:'🤔', a:'"ough" can make many sounds!',         w:['though','through','thought','tough']},
  'ere':    {e:'📍', a:'"ere" making the /air/ sound',         w:['there','where','anywhere','somewhere']},
  'eir':    {e:'👥', a:'"eir" making the /air/ sound',         w:['their','theirs']},
  'or(er)': {e:'🔄', a:'"or" making the /er/ sound',           w:['doctor','mirror','actor','colour']},
  'eau':    {e:'🏰', a:'"eau" making the /oa/ sound',          w:['beau','plateau','chateau']},
},

weeks: [
  {week:1, term:1, theme:'Starting Sounds',            sounds:['s','a','t','i','p'],           trickyWords:['I']},
  {week:2, term:1, theme:'More Basic Sounds',          sounds:['n','ck','e','h','r'],           trickyWords:['the']},
  {week:3, term:1, theme:'New Sounds',                 sounds:['m','d','g','o','u'],            trickyWords:['he','she']},
  {week:4, term:1, theme:'More Sounds',                sounds:['l','f','b','ai','j'],           trickyWords:['we']},
  {week:5, term:1, theme:'Vowel Digraphs',             sounds:['oa','ie','ee','or','z'],        trickyWords:['me']},
  {week:6, term:1, theme:'Final Basic Sounds',         sounds:['w','ng','v','oo','oo2'],        trickyWords:['be']},
  {week:7, term:1, theme:'Digraphs',                   sounds:['y','x','ch','sh','th'],         trickyWords:['was']},
  {week:8, term:1, theme:'Last of the 42',             sounds:['th2','qu','ou','oi','ue'],      trickyWords:['to']},
  {week:9, term:1, theme:'Review & Consolidation',     sounds:['s','a','t','i','p'],            trickyWords:['my'],   review:true, reviewNote:'Review all 42 sounds. Dictation of CVC words. Blending practice with JP Readers.'},
  {week:10,term:1, theme:'Review & Consolidation',     sounds:['n','ck','e','h','r'],           trickyWords:['are'],  review:true, reviewNote:'Students identify sounds in words. Simple sentences from dictation. Revisit digraphs.'},
  {week:11,term:1, theme:'Review & Consolidation',     sounds:['m','d','g','o','u'],            trickyWords:['all'],  review:true, reviewNote:'Word boxes for all 12 tricky words. Reading JP Readers. Encoding regular words.'},
  {week:12,term:1, theme:'Review & Consolidation',     sounds:['l','f','b','ai','j'],           trickyWords:['do'],   review:true, reviewNote:'Class reads aloud with individual sounds, holding up a finger for each. Fluent reading practice.'},
  {week:13,term:2, theme:'Capitals — S A T I P',       sounds:['S','A','T','I','P'],            trickyWords:['your'],         capitals:true},
  {week:14,term:2, theme:'Capitals — N CK E H R',      sounds:['N','CK','E','H','R'],           trickyWords:['come','some'],   capitals:true},
  {week:15,term:2, theme:'Capitals — M D G O U',       sounds:['M','D','G','O','U'],            trickyWords:['said','here'],   capitals:true},
  {week:16,term:2, theme:'Capitals — L F B J W',       sounds:['L','F','B','J','W'],            trickyWords:['there','they'],  capitals:true},
  {week:17,term:2, theme:'ay & a_e for /ai/ sound',    sounds:['ay','a_e','V','Y','Q'],         trickyWords:['go','so']},
  {week:18,term:2, theme:'oy & o_e alternatives',      sounds:['oy','o_e','ew','ow(oh)','oe'],  trickyWords:['do','by']},
  {week:19,term:2, theme:'Long /ee/ alternatives',     sounds:['ee','ea','ie','y(ee)','e_e'],   trickyWords:['old']},
  {week:20,term:2, theme:'Long /ie/ alternatives',     sounds:['i_e','igh','y(ie)','ie','ey'],  trickyWords:['give','live']},
  {week:21,term:2, theme:'Long /oo/ alternatives',     sounds:['u_e','ue','ew','ui','oo2'],     trickyWords:['little','some']},
  {week:22,term:2, theme:'ou / ow alternatives',       sounds:['ow(ou)','ou','ow(oh)','oa','oe'],trickyWords:['down','now']},
  {week:23,term:2, theme:'/ar/ and /or/ alternatives', sounds:['ar','or','aw','au','al'],        trickyWords:['when','what','why']},
  {week:24,term:2, theme:'ew for /ue/ & /oo/',         sounds:['ew','ue','u_e','oo2','ui'],     trickyWords:['who','which','where']},
  {week:25,term:3, theme:'Complex /ou/ patterns',      sounds:['ew','ow(ou)','air','are','ear'],trickyWords:['any','many']},
  {week:26,term:3, theme:'Long /ie/ consolidation',    sounds:['igh','ie','i_e','y(ie)','eigh'],trickyWords:['more','before','because']},
  {week:27,term:3, theme:'Complex /aw/ patterns',      sounds:['aw','au','al','augh','ough'],   trickyWords:['other','were']},
  {week:28,term:3, theme:'Long /ai/ consolidation',    sounds:['ai','ay','a_e','eigh','ey'],    trickyWords:['because','want']},
  {week:29,term:3, theme:'Long /ee/ consolidation',    sounds:['ee','ea','e_e','y(ee)','ey'],   trickyWords:['say','stay','put']},
  {week:30,term:3, theme:'Long /oa/ consolidation',    sounds:['oa','ow(oh)','o_e','oe','eau'], trickyWords:['could','should','would']},
  {week:31,term:3, theme:'/oo/ alternatives review',   sounds:['oo2','ue','ew','u_e','ui'],     trickyWords:['right','two','four']},
  {week:32,term:3, theme:'Spellings review',           sounds:['ie','igh','i_e','y(ie)','eigh'],trickyWords:['does','made','their']},
  {week:33,term:3, theme:'/aw/ alternatives review',   sounds:['au','aw','al','ough','augh'],   trickyWords:['once','upon','teach']},
  {week:34,term:3, theme:'/er/ alternatives review',   sounds:['er','ir','ur','ear','or(er)'],  trickyWords:['eight','also']},
  {week:35,term:3, theme:'/air/ alternatives',         sounds:['air','are','ear','ere','eir'],  trickyWords:['done','love','come','cover']},
  {week:36,term:3, theme:'Final Review & Assessment',  sounds:['oi','oy','ou','ow(ou)','qu'],   trickyWords:['every','after','mother','father']},
],

terms: [
  {id:1, name:'Term 1', sub:'The 42 Basic Sounds',         bg:'#EFF6FF', accent:'#2563EB', badge:'#BFDBFE'},
  {id:2, name:'Term 2', sub:'Capitals & Alternatives',     bg:'#F0FDF4', accent:'#16A34A', badge:'#BBF7D0'},
  {id:3, name:'Term 3', sub:'Complex Spelling Patterns',   bg:'#FFFBEB', accent:'#D97706', badge:'#FDE68A'},
],

days: ['Monday','Tuesday','Wednesday','Thursday','Friday'],
};
